version: "3.9"

services:
  app:
    build: .
    container_name: loan-application-service
    restart: always
    ports:
      - "5500:5500"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/loan_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15
    container_name: loan-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loan_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d loan_db"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
